#!/usr/bin/env bash
# check-wire-format.sh — fire the receiver's static_asserts without a full build.
#
# THE WIRE FORMAT IS DEFINED BY HAND IN FOUR PLACES: the locator's
# MessageProtocol.hpp, this receiver's copy, the app's Kotlin byte offsets
# (RocketState.kt / FlightDataRepository.kt, pinned by WireLayoutTest.kt), and
# the iOS copy (WireLayoutTests.swift). Nothing but agreement keeps them in
# step, and a mismatch is not a compile error anywhere — it is a rocket whose
# telemetry decodes into the wrong fields.
#
# The static_asserts in those headers ARE the guard. The problem is when they
# fire: only during a full firmware build, which needs the CubeIDE toolchain and
# an IDE-refreshed Debug/ tree (its subdir.mk files are generated by folder scan
# and go stale the moment a source file is added). So the one check most worth
# running before a commit was the one hardest to run.
#
# This runs them in about a second. It compiles each header that carries a
# static_assert as a translation unit of its own, syntax-only: no objects, no
# linking, no Debug/ tree, no makefile.
#
# WHAT IT DOES NOT DO: link, or run anything on the MCU. It proves the sizes and
# offsets the headers assert still hold under the real target compiler and the
# real target's type sizes -- which is the whole of what those asserts claim,
# and is exactly the class of drift that silently breaks a flight.
#
# Usage:
#   Scripts/check-wire-format.sh              # every header carrying asserts
#   ARM_GXX=/path/to/arm-none-eabi-g++ Scripts/check-wire-format.sh

set -u

cd "$(git rev-parse --show-toplevel)"

# --- Toolchain ---------------------------------------------------------------
#
# Not on PATH on the Windows box; it ships inside STM32CubeIDE. On a Mac with a
# toolchain installed normally, `command -v` finds it. ARM_GXX overrides both.
if [ -z "${ARM_GXX:-}" ]; then
  ARM_GXX="$(ls -d /c/ST/STM32CubeIDE_*/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.*/tools/bin/arm-none-eabi-g++.exe 2>/dev/null | head -1)"
fi
if [ -z "${ARM_GXX:-}" ] || [ ! -x "$ARM_GXX" ]; then
  ARM_GXX="$(command -v arm-none-eabi-g++ 2>/dev/null || true)"
fi
if [ -z "${ARM_GXX:-}" ] || [ ! -x "$ARM_GXX" ]; then
  echo "ERROR: arm-none-eabi-g++ not found." >&2
  echo "       Set ARM_GXX=/path/to/arm-none-eabi-g++ and re-run." >&2
  exit 2
fi

# --- Flags -------------------------------------------------------------------
#
# Copied from what the real build uses, read out of Debug/Rocket/**/subdir.mk
# rather than guessed. STM32WL5Mxx is the part, NOT STM32WL55xx -- getting that
# wrong makes the HAL headers fail to resolve in a way that looks like a missing
# include path. CORE_CM4 selects the core; the receiver has no CM0 half.
DEFS="-mcpu=cortex-m4 -DCORE_CM4 -DSTM32WL5Mxx -DUSE_HAL_DRIVER"

INC="-ICore/Inc -ISubGHz_Phy/App -ISubGHz_Phy/Target
     -IDrivers/STM32WLxx_HAL_Driver/Inc -IDrivers/STM32WLxx_HAL_Driver/Inc/Legacy
     -IDrivers/CMSIS/Device/ST/STM32WLxx/Include -IDrivers/CMSIS/Include
     -IMiddlewares/Third_Party/SubGHz_Phy/radio_driver
     -IUtilities/trace/adv_trace -IUtilities/misc -IUtilities/sequencer
     -IUtilities/timer -IUtilities/lpm/tiny_lpm
     -IRocket/Inc -IRocket/Archive/Inc -IRocket/Common/Inc -IRocket/Communication/Inc"

# --- Which headers -----------------------------------------------------------
#
# DISCOVERED, not listed: every header under Rocket/ that carries a
# static_assert is checked, so one added tomorrow is guarded tomorrow rather
# than whenever someone remembers to extend this list. That is the same rule the
# locator's pre-commit hook applies to Tests/.
#
# The cost of discovery is that a header which cannot be included on its own
# fails here. That is a real defect rather than a false alarm -- a header whose
# includes are incomplete is one waiting to break whoever includes it first --
# so the fix is to make it self-contained, not to exempt it.
HEADERS=$(grep -rl 'static_assert' --include='*.hpp' --include='*.h' Rocket 2>/dev/null | sort)

if [ -z "$HEADERS" ]; then
  echo "ERROR: no headers with static_assert found under Rocket/ -- has the tree moved?" >&2
  exit 2
fi

TMPD=$(mktemp -d)
trap 'rm -rf "$TMPD"' EXIT

# The compiler is a native Windows binary; git-bash's $PWD is an msys path
# (/c/...) it cannot open, and the resulting "No such file or directory" reads
# as a missing header rather than a path-format problem. Cost an entire debug
# cycle the first time.
if command -v cygpath >/dev/null 2>&1; then
  ROOT_NATIVE=$(cygpath -m "$PWD")
else
  ROOT_NATIVE="$PWD"
fi

problems=0
assert_failures=0
total_asserts=0

for h in $HEADERS; do
  n=$(grep -c 'static_assert' "$h")
  total_asserts=$((total_asserts + n))
  printf '  %-52s %2d assert(s)  ' "$h" "$n"

  # A TU that includes the header by its full path, so the header's own include
  # guards and dependencies are exercised exactly as a real consumer sees them.
  printf '#include "%s"\nint main(){return 0;}\n' "$ROOT_NATIVE/$h" > "$TMPD/tu.cpp"

  if err=$("$ARM_GXX" -std=gnu++17 -fsyntax-only $DEFS $INC "$TMPD/tu.cpp" 2>&1); then
    echo "ok"
  else
    echo "FAIL"
    printf '%s\n' "$err" | grep -E 'error:|static assertion' | head -6 | sed 's/^/       /'
    problems=$((problems + 1))
    if printf '%s' "$err" | grep -q 'static assertion'; then
      assert_failures=$((assert_failures + 1))
    fi
  fi
done

echo
if [ "$problems" -eq 0 ]; then
  echo "PASS — $total_asserts wire/layout assertion(s) hold under the target compiler."
  exit 0
fi
echo "FAIL — $problems header(s) above." >&2
if [ "$assert_failures" -gt 0 ]; then
  echo "       A size or offset CHANGED. The wire format is defined by hand in FOUR" >&2
  echo "       places: this header, the locator's copy, WireLayoutTest.kt and" >&2
  echo "       WireLayoutTests.swift. Update all of them in the SAME session." >&2
else
  echo "       No assertion fired — these failed to COMPILE, which is a different" >&2
  echo "       problem: a missing include, a toolchain flag, or a header that is not" >&2
  echo "       self-contained. Read the errors above before touching the wire format." >&2
fi
exit 1
